spring :
  datasource:
    url : jdbc:postgresql://localhost:5432/clothes_shop?useSSL=false
    username : mac
    password : 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

